version: '3.5'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: frontend
    restart: unless-stopped
    ports:
      - "80:8080"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    command: /home/node/app/node_modules/.bin/nodemon app.js

volumes:
  node_modules:
